#303187 2. Creation of Month-Quarter-Year Form
vhelperv/4th-module pull request #1
Opened 2023-12-28 14:16 UTC by vhelperv

Створив сутність, форму, схему бази даних, підтему для редагування вигляду сайту. Також додав шаблон та налаштував виведення форми через контролер. Відкорегував вигляд таблиці у підтемі.

2023-12-28 14:38 UTC, Alina-Khmilevska requested changes

2023-12-28 14:38 UTC, Alina-Khmilevska commented on web/modules/custom/helper/templates/table-page.html.twig
> +        <th class="year-table__body-row-ytd" id="row-ytd">{{ form.ytd }}</th> {# Later add id to id #}
Instead of manually writing each row, use a loop.

2023-12-28 14:38 UTC, Alina-Khmilevska commented on web/modules/custom/helper/src/Form/FormTableRow.php
> +}
Need empty line at the end of line

2023-12-28 14:38 UTC, Alina-Khmilevska commented on web/modules/custom/helper/src/Entity/HelperEntity.php
> +}
Need empty line at the end of line

2023-12-28 14:38 UTC, Alina-Khmilevska commented on web/modules/custom/helper/src/Controller/HelperController.php
> +}
Need empty line at the end of line

2023-12-28 14:38 UTC, Alina-Khmilevska commented on web/modules/custom/helper/helper.module
> +}
Need empty line at the end of line

2023-12-28 14:38 UTC, Alina-Khmilevska commented on web/modules/custom/helper/helper.install
> +}
Need empty line at the end of line

2023-12-28 16:31 UTC, vhelperv commented
I corrected the specified errors.

2023-12-29 07:40 UTC, Alina-Khmilevska approved these changes

2023-12-29 08:53 UTC, merged